ASSETS_LIST += \
	filesystem/swordstrike/fighter_jumping_left.sprite \
	filesystem/swordstrike/fighter_jumping_right.sprite \
	filesystem/swordstrike/fighter_left_neutral.sprite \
	filesystem/swordstrike/fighter_right_neutral.sprite \
	filesystem/swordstrike/fighter_sliding_left.sprite \
	filesystem/swordstrike/fighter_sliding_right.sprite \
	filesystem/swordstrike/fighter_left_attack_1.sprite \
	filesystem/swordstrike/fighter_left_attack_2.sprite \
	filesystem/swordstrike/fighter_left_attack_3.sprite \
	filesystem/swordstrike/fighter_left_attack_4.sprite \
	filesystem/swordstrike/fighter_left_attack_5.sprite \
	filesystem/swordstrike/fighter_left_attack_6.sprite \
	filesystem/swordstrike/fighter_left_attack_7.sprite \
	filesystem/swordstrike/fighter_left_attack_8.sprite \
	filesystem/swordstrike/fighter_left_attack_9.sprite \
	filesystem/swordstrike/fighter_left_attack_10.sprite \
	filesystem/swordstrike/fighter_right_attack_1.sprite \
	filesystem/swordstrike/fighter_right_attack_2.sprite \
	filesystem/swordstrike/fighter_right_attack_3.sprite \
	filesystem/swordstrike/fighter_right_attack_4.sprite \
	filesystem/swordstrike/fighter_right_attack_5.sprite \
	filesystem/swordstrike/fighter_right_attack_6.sprite \
	filesystem/swordstrike/fighter_right_attack_7.sprite \
	filesystem/swordstrike/fighter_right_attack_8.sprite \
	filesystem/swordstrike/fighter_right_attack_9.sprite \
	filesystem/swordstrike/fighter_right_attack_10.sprite \
	filesystem/swordstrike/wilhelm_scream.wav64 \
	filesystem/swordstrike/challengers.wav64 \
	filesystem/swordstrike/background_cube_color.t3dm \
	filesystem/swordstrike/background_cube_sand.t3dm \
	filesystem/swordstrike/sand12.ci4.sprite