#ifndef SEQUENCE_INTRODUCTION_GRAPHICS_H
#define SEQUENCE_INTRODUCTION_GRAPHICS_H

#include <libdragon.h>

extern bool sequence_introduction_should_cleanup;

extern bool sequence_introduction_libdragon_logo_started;
extern bool sequence_introduction_libdragon_logo_finished;
extern float sequence_introduction_libdragon_logo_elapsed;

extern int sequence_introduction_frame;
extern int sequence_introduction_current_paragraph_drawn_characters;
extern int sequence_introduction_current_paragraph;
extern int sequence_introduction_current_paragraph_speed;
extern bool sequence_introduction_paragraphs_finished;
extern bool sequence_introduction_current_paragraph_finished;
extern bool sequence_introduction_paragraphs_started;
extern bool sequence_introduction_paragraph_fade_out_started;
extern float sequence_introduction_paragraph_fade_out_elapsed;
extern bool sequence_introduction_paragraph_fade_out_finished;
extern char *sequence_introduction_current_paragraph_string;

extern bool sequence_introduction_mallard_logo_started;
extern bool sequence_introduction_mallard_logo_finished;
extern float sequence_introduction_mallard_logo_elapsed;

extern sprite_t *sequence_introduction_a_button_sprite;
extern sprite_t *sequence_introduction_start_button_sprite;
extern sprite_t *sequence_introduction_mallard_libdragon_sprite;
extern sprite_t *sequence_introduction_mallard_logo_black_sprite;
extern sprite_t *sequence_introduction_mallard_logo_white_sprite;

extern xm64player_t sequence_introduction_xm;

void sequence_introduction_draw_libdragon_logo(float deltatime);
void sequence_introduction_draw_mallard_logo(float deltatime);
void sequence_introduction_draw_press_start_to_skip();
void sequence_introduction_draw_press_a_for_next();
void sequence_introduction_draw_paragraph(float deltatime);

#endif // SEQUENCE_INTRODUCTION_GRAPHICS_H
