ASSETS_LIST += \
	filesystem/hydraharmonics/face-0.ci4.sprite \
	filesystem/hydraharmonics/face-1.ci4.sprite \
	filesystem/hydraharmonics/face-2.ci4.sprite \
	filesystem/hydraharmonics/face-3.ci4.sprite \
	filesystem/hydraharmonics/neck-0.ci4.sprite \
	filesystem/hydraharmonics/neck-1.ci4.sprite \
	filesystem/hydraharmonics/neck-2.ci4.sprite \
	filesystem/hydraharmonics/neck-3.ci4.sprite \
	filesystem/hydraharmonics/topback-0.ci4.sprite \
	filesystem/hydraharmonics/topback-1.ci4.sprite \
	filesystem/hydraharmonics/topback-2.ci4.sprite \
	filesystem/hydraharmonics/topback-3.ci4.sprite \
	filesystem/hydraharmonics/shell-0.ci4.sprite \
	filesystem/hydraharmonics/shell-1.ci4.sprite \
	filesystem/hydraharmonics/shell-2.ci4.sprite \
	filesystem/hydraharmonics/shell-3.ci4.sprite \
	filesystem/hydraharmonics/eyes-0.ci4.sprite \
	filesystem/hydraharmonics/eyes-1.ci4.sprite \
	filesystem/hydraharmonics/eyes-2.ci4.sprite \
	filesystem/hydraharmonics/eyes-3.ci4.sprite \
	filesystem/hydraharmonics/eyelid-0.ci4.sprite \
	filesystem/hydraharmonics/eyelid-1.ci4.sprite \
	filesystem/hydraharmonics/eyelid-2.ci4.sprite \
	filesystem/hydraharmonics/eyelid-3.ci4.sprite \
	filesystem/hydraharmonics/cheek-0.ci4.sprite \
	filesystem/hydraharmonics/cheek-1.ci4.sprite \
	filesystem/hydraharmonics/cheek-2.ci4.sprite \
	filesystem/hydraharmonics/cheek-3.ci4.sprite \
	filesystem/hydraharmonics/effects-0.ci4.sprite \
	filesystem/hydraharmonics/effects-1.ci4.sprite \
	filesystem/hydraharmonics/effects-2.ci4.sprite \
	filesystem/hydraharmonics/effects-3.ci4.sprite \
	filesystem/hydraharmonics/effects-4.ci4.sprite \
	filesystem/hydraharmonics/grin-0.ci4.sprite \
	filesystem/hydraharmonics/grin-1.ci4.sprite \
	filesystem/hydraharmonics/grin-2.ci4.sprite \
	filesystem/hydraharmonics/grin-3.ci4.sprite \
	filesystem/hydraharmonics/hats.ci4.sprite \
	filesystem/hydraharmonics/legs-0.ci4.sprite \
	filesystem/hydraharmonics/legs-1.ci4.sprite \
	filesystem/hydraharmonics/legs-2.ci4.sprite \
	filesystem/hydraharmonics/legs-3.ci4.sprite \
	filesystem/hydraharmonics/note-0.ci4.sprite \
	filesystem/hydraharmonics/note-1.ci4.sprite \
	filesystem/hydraharmonics/note-2.ci4.sprite \
	filesystem/hydraharmonics/note-3.ci4.sprite \
	filesystem/hydraharmonics/note-4.ci4.sprite \
	filesystem/hydraharmonics/sign-0.ci4.sprite \
	filesystem/hydraharmonics/sign-1.ci4.sprite \
	filesystem/hydraharmonics/sign-2.ci4.sprite \
	filesystem/hydraharmonics/sign-3.ci4.sprite \
	filesystem/hydraharmonics/hill-0.ci4.sprite \
	filesystem/hydraharmonics/hill-1.ci4.sprite \
	filesystem/hydraharmonics/hill-2.ci4.sprite \
	filesystem/hydraharmonics/hill-3.ci4.sprite \
	filesystem/hydraharmonics/floor-bottom.ci4.sprite \
	filesystem/hydraharmonics/floor-light.ci4.sprite \
	filesystem/hydraharmonics/floor-dark.ci4.sprite \
	filesystem/hydraharmonics/curtain.ci4.sprite \
	filesystem/hydraharmonics/panel-corner-top.ci4.sprite \
	filesystem/hydraharmonics/panel-corner-bot.ci4.sprite \
	filesystem/hydraharmonics/panel-bg.ci4.sprite \
	filesystem/hydraharmonics/panel-rope.ci4.sprite \
	filesystem/hydraharmonics/button-a.ci4.sprite \
	filesystem/hydraharmonics/button-l.ci4.sprite \
	filesystem/hydraharmonics/button-r.ci4.sprite \
	filesystem/hydraharmonics/button-z.ci4.sprite \
	filesystem/hydraharmonics/button-cup.ci4.sprite \
	filesystem/hydraharmonics/button-cdown.ci4.sprite \
	filesystem/hydraharmonics/button-dup.ci4.sprite \
	filesystem/hydraharmonics/button-ddown.ci4.sprite \
	filesystem/hydraharmonics/Superclarendon-Regular-01.font64 \
	filesystem/hydraharmonics/slide-whistle-up.wav64 \
	filesystem/hydraharmonics/slide-whistle-down.wav64 \
	filesystem/hydraharmonics/drumroll.wav64 \
	filesystem/hydraharmonics/hit-0.wav64 \
	filesystem/hydraharmonics/hit-1.wav64 \
	filesystem/hydraharmonics/hit-2.wav64 \
	filesystem/hydraharmonics/hit-3.wav64 \
	filesystem/hydraharmonics/gulp.wav64 \
	filesystem/hydraharmonics/aah.wav64 \
	filesystem/hydraharmonics/eww.wav64 \
	filesystem/hydraharmonics/ow.wav64 \
	filesystem/hydraharmonics/hydraharmonics.xm64 \

filesystem/hydraharmonics/Superclarendon-Regular-01.font64: MKFONT_FLAGS += --outline 1 --size 12
